### ISSUE TITLE
Partie.html

### ISSUE THREAD

**Issue by AdrianUtge** [gabriel-dahan/connect4-game#2]
Salut, comme j'ai fait le ficher game.html qui se génère de manière dynamique il faut remplacer le pointage du partie.html

Adrian.

**Comment by gabriel-dahan** [comment]
Le pointage du CSS ?

**Comment by AdrianUtge** [comment]
le pointage du css et des pages en amont (login)

**Comment by gabriel-dahan** [comment]
Je vois je vois, on fera ça après en vrai, tant que ça fonctionne de ce côté. Après il suffira juste de merge et de modifier un peu pour que ça fonctionne dans le main
